### ISSUE TITLE
Installation issue: undefined function ray()

### ISSUE THREAD

**Issue by netcarver** [robertweiss/AutoPageClassAnnotations#1]
@robertweiss Hello Robert,

Just trying out this module and got the following error on line 254...

![image](https://github.com/robertweiss/AutoPageClassAnnotations/assets/16049/ed8abc3f-ba8d-4bc3-93aa-310865924500)

**Comment by robertweiss** [comment]
Hi @netcarver, thanks for the feedback! I forgot to remove some debug calls to ray (pretty useful tool btw: https://myray.app/docs/getting-started/introduction 😄), issue is fixed now.
